# This is a basic workflow that is manually triggered

name: Finish release workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
 start-realease:
  name: Start Release Workflow
  
  runs-on: ubuntu-latest
  steps:
    - uses: actions/checkout@v2
    - run: git config --global user.email "workflow@example.com"
    - run: git config --global user.name "Workflow"
    - uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
          distribution: 'adopt'
          java-version: '11'
          java-package: jdk
    - name: Set up Maven
      uses: stCarolas/setup-maven@v4
      with:
        maven-version: 3.5.4
    - name: Finilize Release branch   
      run: mvn -B gitflow:release-finish
   
